In [1]:
import HAT
import numpy as np
import scipy as sp
import networkx as nx

In [2]:
W = np.random.randint(2,size=(15,20))

In [3]:
W = np.random.randint(2,size=(15,20))
HG = HAT.Hypergraph(W)
# HG.draw()

In [4]:
# HAT.draw.incidencePlot(HG)

In [5]:
I = np.array([[1, 1, 1, 0],
              [1, 1, 0, 1],
              [1, 0, 1, 1],
              [0, 1, 1, 1]])

HG = HAT.Hypergraph(I)
A = HG.adjTensor()
D = HG.degreeTensor()
L = HG.laplacianTensor()

In [6]:
I = np.array([[1, 1, 1, 0],
              [1, 1, 0, 1],
              [1, 0, 1, 1]])
HG = HAT.Hypergraph(I)
C = HG.cliqueGraph()
L = HG.lineGraph()
S = HG.starGraph()

In [7]:
B = HG.laplacianMatrix("Bolla")
R = HG.laplacianMatrix("Rodriguez")
Z = HG.laplacianMatrix("Zhou")

In [8]:
HG1 = HAT.uniformErdosRenyi(6,4,3)
HG2 = HAT.uniformErdosRenyi(6,4,3)

In [9]:
D1 = HAT.directSimilarity(HG1, HG2, 'Hamming')
print(D1)
D2 = HAT.directSimilarity(HG1, HG2, 'Spectral-S')
print(D2)
D3 = HAT.directSimilarity(HG1, HG2, 'centrality')
print(D3)

0.12380952380952381
4.8936807962684945
0.11292370628198518


In [10]:
G1 = HG1.cliqueGraph()
G2 = HG2.cliqueGraph()

D1 = HAT.indirectSimilarity(G1, G2, 'Hamming')
D2 = HAT.indirectSimilarity(G1, G2, 'Jaccard')
D3 = HAT.indirectSimilarity(G1, G2, 'deltaCon')
D4 = HAT.indirectSimilarity(G1, G2, 'Spectral')
# Centrality D5 = HAT.indirectSimilarity(G1, G2, 'Jaccard')
# D6 = HAT.indirectSimilarity(G1, G2, 'Jaccard')
print(D1)
print(D2)
print(D3)
print(D4)



0.26666666666666666
0.8571428571428572
0.015531368962205985
0.24049759969471576


In [12]:
HG = HAT.uniformErdosRenyi(10,9,3)
print(HG.tensorEntropy())
print(HG.matrixEntropy())
print(HG.clusteringCoef())
print(HG.avgDistance())

2.2068854769292123
-inf
0.4503571428571428
1.5777777777777777


In [30]:
HG = HAT.uniformErdosRenyi(9,9,4)
HG.centrality(model='LogExp')

(array([0.10499828, 0.112828  , 0.09487666, 0.09487666, 0.12486471,
        0.112828  , 0.10499828, 0.12486471, 0.12486471]),
 array([0.11111111, 0.11111111, 0.11111111, 0.11111111, 0.11111111,
        0.11111111, 0.11111111, 0.11111111, 0.11111111]))

In [31]:
B = HG.ctrbk([1, 3])
B

(9, 2)
(9, 10)
(9, 2)
(9, 10)
(9, 2)
(9, 10)
(9, 2)
(9, 10)
(9, 2)
(9, 10)
(9, 2)
(9, 10)
(9, 2)
(9, 10)
(9, 2)
(9, 10)
(9, 2)
(9, 10)
(9, 2)


array([[ 0.,  0.],
       [ 0.,  1.],
       [ 0.,  0.],
       [-1.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.]])

In [ ]:
sp.stats.entropy(np.array([ 6.00000000e+00, -5.33573783e-16,  6.00000000e+00]))

In [ ]:
D3 = HAT.indirectSimilarity(G1, G2, 'deltaCon')

In [ ]:
# HG1.degreeTensor()
# order = int(sum(HG1.IM[:,0]))
# np.ones(order)
M1 = nx.adjacency_matrix(G1).todense()
print(M1)
D1 = np.diag(sum(M1))
print(D1)